### ISSUE TITLE
Separate boxes for Website

### ISSUE THREAD

**Issue by MisterCookiez** [BumpBotDiscord/bump#3]
In a bottom portion of the website, aiming for separate links that go to the wiki, donate, and other stuff. I need **6** things to add.

@SlowestLoris @ATMG Ideas requested.

Preferably something that looks like the bottom of the [Discord RPG Website](https://discorddungeons.me/).

**Comment by SlowestLoris** [comment]
Patreon, Paypal, Login, View Stats

**Comment by MisterCookiez** [comment]
Will be added. I would like some details about each of those, though. And how would I implement a `view stats` for it 🤔
